# Generated by Django 4.0.1 on 2022-01-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0009_project_manager_from_time_project_manager_until_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='until_time',
        ),
        migrations.AddField(
            model_name='student',
            name='desire_times',
            field=models.TextField(blank=True),
        ),
    ]
