# Generated by Django 4.0.1 on 2022-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
