# Generated by Django 4.0.1 on 2022-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_user',
            name='tg_id',
            field=models.IntegerField(unique=True),
        ),
    ]
