# Generated by Django 4.0.1 on 2022-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0005_alter_tg_user_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desired_time',
        ),
        migrations.AddField(
            model_name='student',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available from a time'),
        ),
        migrations.AddField(
            model_name='student',
            name='until_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available until a time'),
        ),
    ]
