# Generated by Django 4.0.1 on 2022-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0006_remove_student_desired_time_student_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tg_user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
