# Generated by Django 4.0.1 on 2022-01-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0007_tg_user_is_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tg_id',
            new_name='tg_user',
        ),
        migrations.AddField(
            model_name='project_manager',
            name='tg_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='project_organizer.tg_user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tg_user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tg_user',
            name='tg_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
