# Generated by Django 4.0.1 on 2022-01-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0008_rename_tg_id_student_tg_user_project_manager_tg_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_manager',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available from a time'),
        ),
        migrations.AddField(
            model_name='project_manager',
            name='until_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available until a time'),
        ),
    ]
